//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Работа
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> Date_of_birthday { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> id_Gender { get; set; }
        public Nullable<int> id_Realty_type { get; set; }
        public double Prepayment { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Realty_type Realty_type { get; set; }
    }
}
