//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Работа
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realty
    {
        public int id { get; set; }
        public string Title { get; set; }
        public Nullable<double> Price { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
        public string Square { get; set; }
        public Nullable<int> id_Realty_type { get; set; }
    
        public virtual Realty_type Realty_type { get; set; }
    }
}
